/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of Stats.xs. Do not edit this file, edit Stats.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Stats.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "const-c.inc"

#line 20 "Stats.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 162 "Stats.c"

/* INCLUDE:  Including 'const-xs.inc' from 'Stats.xs' */


XS_EUPXS(XS_Local__Stats_constant); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_constant)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 187 "Stats.c"
	SV *	sv = ST(0)
;
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Local::Stats macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Local::Stats macro %s, used",
				   s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Local::Stats macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 264 "Stats.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'Stats.xs' from 'const-xs.inc' */


XS_EUPXS(XS_Local__Stats_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, coderef");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	class = (char *)SvPV_nolen(ST(0))
;
	SV *	coderef = ST(1)
;
	SV *	RETVAL;
#line 18 "Stats.xs"
        ENTER; SAVETMPS;
        HV *hash = (HV *)sv_2mortal((SV *)newHV());
        hv_store(hash, "get_settings", strlen("get_settings"), newSVsv(coderef), 0);
        hv_store(hash, "stats", strlen("stats"), newRV(sv_2mortal((SV *)newHV())), 0);
        SV *href = newRV((SV *)hash);
        SV *self = sv_bless(href, gv_stashpv(class, TRUE));
        FREETMPS; LEAVE;
        XPUSHs(sv_2mortal(self));
#line 297 "Stats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Local__Stats_add); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_add)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "self, name, value");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	self = ST(0)
;
	char *	name = (char *)SvPV_nolen(ST(1))
;
	double	value = (double)SvNV(ST(2))
;
#line 33 "Stats.xs"
        ENTER; SAVETMPS;
        if (!(SvOK(self) && SvROK(self))) {
            croak("self must be a hashref");
        }
        if (!(sv_isobject(self) && sv_isa(self, "Local::Stats"))) {
            croak("self must be an Local::Stats object");
        }
        HV *hself = (HV *)(SvRV(self));
        if (!hv_exists(hself, "stats", strlen("stats"))) {
            croak("self->{stats} key expected");
        }
        SV **_stats = hv_fetch(hself, "stats", strlen("stats"), 0);
        if (!_stats) {
            croak("self->{stats} hashref expected. NULL found");
        }
        HV *stats = (HV *)(SvRV(*_stats));
        if (!hv_exists(stats, name, strlen(name))) {
            if (!hv_exists(hself, "get_settings", strlen("get_settings"))) {
                croak("self->{get_settings} member function expected");
            }
            SV **_get_settings_sub = hv_fetch(hself, "get_settings", strlen("get_settings"), 0);
            if (!(_get_settings_sub && SvTYPE(SvRV(*_get_settings_sub)) == SVt_PVCV)) {
                croak("self->{get_settings} expected to be a sub");
            }
            SV *get_settings_sub = SvRV(*_get_settings_sub);
            PUSHMARK(SP);
            XPUSHs(sv_2mortal(newSVpv(name, strlen(name))));
            PUTBACK;
            int count = call_sv(get_settings_sub, G_ARRAY);
            SPAGAIN;
            HV *params = (HV *)sv_2mortal((SV *)newHV());
            int i;
            for (i = 0; i < count; ++i) {
                SV *param = newSVsv(POPs);
                char *param_name = (char *)SvPV_nolen(param);
                hv_store(params, param_name, strlen(param_name), newSV(0), 0);
            }
            SV *rparams = newRV((SV *)params);
            hv_store(stats, name, strlen(name), rparams, 0);
            SV *rstats = newRV((SV *)stats);
            hv_store(hself, "stats", strlen("stats"), rstats, 0);
            self = newRV((SV *)hself);
        }
        SV **_metric_stats = hv_fetch(stats, name, strlen(name), 0);
        if (!(_metric_stats && SvTYPE(SvRV(*_metric_stats)) == SVt_PVHV)) {
            croak("self->{stats}->{%s} expected to be a hashref", name);
        }
        HV *metric_stats = (HV *)SvRV(*_metric_stats);
        if (hv_exists(metric_stats, "avg", strlen("avg"))) {
            // Пытаемся достать сохранённое количество замеров
            if (!hv_exists(hself, "_stats", strlen("_stats"))) {
                HV *inner_stats = (HV *)sv_2mortal((SV *)newHV());
                hv_store(hself, "_stats", strlen("_stats"), newRV((SV *)inner_stats), 0);
            }
            SV **_inner_stats = hv_fetch(hself, "_stats", strlen("_stats"), 0);
            if (!(_inner_stats && SvTYPE(SvRV(*_inner_stats)) == SVt_PVHV)) {
                croak("self->{_stats} expected to be a hashref");
            }
            HV *inner_stats = (HV *)(SvRV(*_inner_stats));
            if (!hv_exists(inner_stats, name, strlen(name))) {
                HV *inner_stats_metric = (HV *)sv_2mortal((SV *)newHV());
                hv_store(inner_stats_metric, "cnt", strlen("cnt"), newSVuv(0), 0);
                SV *r_inner_stats_metric = newRV((SV *)inner_stats_metric);
                hv_store(inner_stats, name, strlen(name), r_inner_stats_metric, 0);
            }
            SV **_inner_stats_metric = hv_fetch(inner_stats, name, strlen(name), 0);
            if (!(_inner_stats_metric && SvTYPE(SvRV(*_inner_stats_metric)) == SVt_PVHV)) {
                croak("self->{_stats}->{%s} expected to be a hashref", name);
            }
            HV *inner_stats_metric = (HV *)(SvRV(*_inner_stats_metric));
            if (!hv_exists(inner_stats_metric, "cnt", strlen("cnt"))) {
                hv_store(inner_stats_metric, "cnt", strlen("cnt"), newSVuv(0), 0);
            }
            SV **_inner_stats_metric_cnt = hv_fetch(inner_stats_metric, "cnt", strlen("cnt"), 0);
            if (!(_inner_stats_metric_cnt && SvTYPE(*_inner_stats_metric_cnt) == SVt_IV)) {
                croak("self->{_stats}->{%s}->{cnt} expected to be a uint", name);
            }
            unsigned int cnt;
            cnt = SvUV(*_inner_stats_metric_cnt);
            // Пересчитываем cnt и avg
            SV **_metric_stats_avg = hv_fetch(metric_stats, "avg", strlen("avg"), 0);
            if (!(_metric_stats_avg)) {
                croak("self->{stats}->{%s}->{avg} wasn't expected to be NULL", name);
            }
            double avg;
            if (SvTYPE(*_metric_stats_avg) == SVt_NULL) {
                cnt = 1;
                avg = value;
            } else {
                avg = SvNV(*_metric_stats_avg);
                avg = (avg * cnt + value) / (cnt + 1);
                ++cnt;
            }
            hv_store(metric_stats, "avg", strlen("avg"), newSVnv(avg), 0);
            // Сохраняем результат inner_stats
            hv_store(inner_stats_metric, "cnt", strlen("cnt"), newSVuv(cnt), 0);
            SV *rinner_stats_metric = newRV((SV *)inner_stats_metric);
            hv_store(inner_stats, name, strlen(name), rinner_stats_metric, 0);
            SV *rinner_stats = newRV((SV *)inner_stats);
            hv_store(hself, "_stats", strlen("_stats"), rinner_stats, 0);
            self = newRV((SV *)hself);
        }
        if (hv_exists(metric_stats, "cnt", strlen("cnt"))) {
            SV **_metric_stats_cnt = hv_fetch(metric_stats, "cnt", strlen("cnt"), 0);
            if (!(_metric_stats_cnt)) {
                croak("self->{stats}->{%s}->{cnt} wasn't expected to be NULL", name);
            }
            double cnt;
            if (SvTYPE(*_metric_stats_cnt) == SVt_NULL) {
                cnt = 1;
            } else {
                cnt = SvUV(*_metric_stats_cnt);
                ++cnt;
            }
            hv_store(metric_stats, "cnt", strlen("cnt"), newSVuv(cnt), 0);
        }
        if (hv_exists(metric_stats, "min", strlen("min"))) {
            SV **_metric_stats_min = hv_fetch(metric_stats, "min", strlen("min"), 0);
            if (!(_metric_stats_min)) {
                croak("self->{stats}->{%s}->{min} wasn't expected to be NULL", name);
            }
            double min;
            if (SvTYPE(*_metric_stats_min) == SVt_NULL) {
                min = value;
            } else {
                min = SvNV(*_metric_stats_min);
                if (value < min) {
                    min = value;
                }
            }
            hv_store(metric_stats, "min", strlen("min"), newSVnv(min), 0);
        }
        if (hv_exists(metric_stats, "max", strlen("max"))) {
            SV **_metric_stats_max = hv_fetch(metric_stats, "max", strlen("max"), 0);
            if (!(_metric_stats_max)) {
                croak("self->{stats}->{%s}->{max} wasn't expected to be NULL", name);
            }
            double max;
            if (SvTYPE(*_metric_stats_max) == SVt_NULL) {
                max = value;
            } else {
                max = SvNV(*_metric_stats_max);
                if (value > max) {
                    max = value;
                }
            }
            hv_store(metric_stats, "max", strlen("max"), newSVnv(max), 0);
        }
        if (hv_exists(metric_stats, "sum", strlen("sum"))) {
            SV **_metric_stats_sum = hv_fetch(metric_stats, "sum", strlen("sum"), 0);
            if (!(_metric_stats_sum)) {
                croak("self->{stats}->{%s}->{sum} wasn't expected to be NULL", name);
            }
            double sum;
            if (SvTYPE(*_metric_stats_sum) == SVt_NULL) {
                sum = value;
            } else {
                sum = SvNV(*_metric_stats_sum);
                sum += value;
            }
            hv_store(metric_stats, "sum", strlen("sum"), newSVnv(sum), 0);
        }
        // Обновляем информацию в объекте
        SV *rmetric_stats = newRV((SV *)metric_stats);
        hv_store(stats, name, strlen(name), rmetric_stats, 0);
        SV *rstats = newRV((SV *)stats);
        hv_store(hself, "stats", strlen("stats"), rstats, 0);
        self = newRV((SV *)hself);
        FREETMPS; LEAVE;
#line 489 "Stats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Local__Stats_stat); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_stat)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	self = ST(0)
;
	SV *	RETVAL;
#line 207 "Stats.xs"
        ENTER; SAVETMPS;
        if (!(SvOK(self) && SvROK(self))) {
            croak("self must be a hashref");
        }
        if (!(sv_isobject(self) && sv_isa(self, "Local::Stats"))) {
            croak("self must be an Local::Stats object");
        }
        HV *hself = (HV *)(SvRV(self));
        if (!hv_exists(hself, "stats", strlen("stats"))) {
            croak("self->{stats} key expected");
        }
        SV **_stats = hv_fetch(hself, "stats", strlen("stats"), 0);
        if (!_stats) {
            croak("self->{stats} hashref expected. NULL found");
        }
        HV *stats = (HV *)(SvRV(*_stats));
        hv_iterinit(stats);
        SV *_metric_stats;
        char *metric_name;
        int metric_name_length;
        HV *result_stats = (HV *)(sv_2mortal((SV *)newHV()));
        while ((_metric_stats = hv_iternextsv(stats, &metric_name, &metric_name_length))) {
            if (!SvTYPE(SvRV(_metric_stats)) == SVt_PVHV) {
                croak("Expected entries in self->{stats} to be hashrefs");
            }
            HV *metric_stats = (HV *)(SvRV(_metric_stats));
            hv_iterinit(metric_stats);
            SV *stat_value;
            char *stat_name;
            int stat_name_length;
            int keys_count = 0;
            HV *buffer_metric_stats = (HV *)sv_2mortal((SV *)newHV());
            while ((stat_value = hv_iternextsv(metric_stats, &stat_name, &stat_name_length))) {
                ++keys_count;
                hv_store(buffer_metric_stats, stat_name, stat_name_length, newSVsv(stat_value), 0);
                hv_store(metric_stats, stat_name, stat_name_length, newSV(0), 0);
            }
            if (keys_count > 0) {
                SV *rresult_metric_stats = newRV((SV *)buffer_metric_stats);
                hv_store(result_stats, metric_name, metric_name_length, rresult_metric_stats, 0);
            }
            SV *rmetric_stats = newRV((SV *)metric_stats);
            hv_store(stats, metric_name, metric_name_length, rmetric_stats, 0);
        }
        SV *rresult_stats = newRV((SV *)result_stats);
        FREETMPS; LEAVE;
        XPUSHs(sv_2mortal(rresult_stats));
#line 556 "Stats.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Local__Stats); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Local__Stats)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Local::Stats::constant", XS_Local__Stats_constant, file);
        newXS("Local::Stats::new", XS_Local__Stats_new, file);
        newXS("Local::Stats::add", XS_Local__Stats_add, file);
        newXS("Local::Stats::stat", XS_Local__Stats_stat, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

